substitutions:
  device_name: sense-u
  friendly_name: Sense-U

esphome:
  name: ${device_name}

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

external_components:
  - source: github://andyboeh/esphome-sense-u
    components: senseu


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name} HS"
    password: !secret Fallback_Hotspot
    ap_timeout: 1min

esp32_ble_tracker:

ble_client:
  - mac_address: AA:BB:CC:DD:EE:FF #update with your Sense-U's MAC address
    id: my_senseu_ble

senseu:
  - ble_client_id: my_senseu_ble
    id: my_senseu
    # baby_code is optional. Needs to be retrieved during pairing phase.
    # This allows using the Sense-U with multiple devices, e.g. at different
    # locations.
    
    # baby_code: aabbccddeeff

# Example configuration entry
sensor:
  - platform: senseu
    id: my_senseu
    breath_rate: 
      name: ${friendly_name} Breath Rate
    temperature: 
      name: ${friendly_name} Temperature
    humidity: 
      name: ${friendly_name} Humidity
    battery_level:
      name: ${friendly_name} Battery Level
    connected:
      name: ${friendly_name} Connected
  # Uptime sensor
  - platform: uptime
    name: ${friendly_name} Uptime
  # WiFi Signal sensor
  - platform: wifi_signal
    name: ${friendly_name} Wifi Signal
    update_interval: 60s
    
# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
  - platform: senseu
    id: my_senseu
    posture:
      name: ${friendly_name} Posture
    status:
      name: ${friendly_name} State

binary_sensor:
  - platform: senseu
    id: my_senseu
    breath:
      name: ${friendly_name} Breath Alarm
    posture:
      name: ${friendly_name} Posture Alarm
    temperature:
      name: ${friendly_name} Temperature Alarm
    battery:
      name: ${friendly_name} Battery Alarm

switch:
  - platform: senseu
    senseu_id: my_senseu
    name: ${friendly_name} Power Switch
